[book]
language = "no"
title = "C++ og Rust: En sammenlikning"

[build]
build-dir = "book"

[output.html]
additional-js = ["jquery.js", "disable-devtool.js", "lang.js"]
additional-css = ["lang.css"]

[output.html.playground]
editable = true

[preprocessor]

[preprocessor.lang]
command = "mdbook-lang"
server = "http://127.0.0.1:3333/api/v1/build-code"
cpp-enable = true
java-enable = false
go-enable = false
python-enable = false
javascript-enable = false
typescript-enable = false
scheme-enable = false
editable = true
disable-devtool-auto = false
disable-menu = false
clear-log = false
disable-select = false
disable-copy = false
disable-cut = false
disable-paste = false
ace-strict = false
